### ISSUE TITLE
Add test cases with GTest

### ISSUE THREAD

**Issue by andylizf** [The-Goo-Goo-Gang/nogo-backend#11]
1. Write test cases.
2. Integrate into GitHub Actions.
3. Display the real-time coverage rate on README, and ensure it is 100% all the time.

**Comment by weizihong** [comment]
Do we have to add test cases for new functions frequently to ensure the coverage rate is 100%?

**Comment by weizihong** [comment]
The test case should stop after it finishes its work, but now it seems stuck in somewhere. I could't solve this problem. @andylizf

**Comment by weizihong** [comment]
Sorry, I forgot to pull. I will finish it soon.
