### ISSUE TITLE
White players can't give up.

### ISSUE THREAD

**Issue by weizihong** [The-Goo-Goo-Gang/nogo-backend#13]
White players giving up will cause logic_error(Black is not allowed to concede).

**Comment by andylizf** [comment]
Could you provide more details? Like the messages or playing steps.

**Comment by andylizf** [comment]
```c++
if (players[current.role] != player)
    throw std::logic_error(player.name + " not allowed to concede");
```
I guess something may be wrong with the condition.

**Comment by weizihong** [comment]
Frontend show  ` sendData {"op":200003,"data1":"","data2":""} `
But in backend we wrote:
```
case OpCode::GIVEUP_OP: {
    auto role { data2 == "b" ? Role::BLACK : data2 == "w" ? Role::WHITE
                                                                                            : Role::NONE };
```
This might cause some problem.

**Comment by andylizf** [comment]
No. As #14 said, when the `role` is `NONE`, `contest.players[{ participant, role }]` will find the player by index `participant`.

**Comment by weizihong** [comment]
This problem is caused by this in `playercouple`.
```
if (player.role == Role::NONE) 
            return player.participant == player1.participant ? player1 : player2;
```
In a local game, players use the same `participant`, so when the `role` is `NONE`, `contest.players[{ participant, role }]` would always find `player1`

**Comment by weizihong** [comment]
No, but I fixed it in the latest commit.
