### ISSUE TITLE
If the server encounters a fatal error and simply quits, then the logs are lost.

### ISSUE THREAD

**Issue by andylizf** [The-Goo-Goo-Gang/nogo-backend#32]
When an exception such as Player Already Exists is thrown, the server will simply exit without leaving any logs.

**Comment by weizihong** [comment]
This should be related to the settings in log.hpp. ` logger->flush_on(spdlog::level::critical) ` means send out the logs in the buffer when a critical log was recorded. You can change it to  ` logger->flush_on(spdlog::level::info) ` to solve this problem. But it would let the program become slower.
